### ISSUE TITLE
模型结果

### ISSUE THREAD

**Issue by TTJ520** [zfan20/STOSA#2]
您好，打扰您一下。下载的代码运行的结果跟论文中的结果差距很大，能否告诉一下论文中每个数据集的最优参数设置？万分感谢

**Comment by zfan20** [comment]
The performance is pretty sensitive to the pvn_weight. I found that 0.005 achieves the best. You can try to search for other hyperparameters, but i think the given ones should achieve good results.

**Comment by TTJ520** [comment]
![原版](https://user-images.githubusercontent.com/102462985/175268331-11bca36a-8e1c-4bb5-bb42-947f72d62fa5.PNG)

![原版](https://user-images.githubusercontent.com/102462985/175268415-2f19ebaf-4b9f-4f22-87d2-052116b7a288.PNG)
我采用的是您给的参数设置，也是按照要求的运行方式来运行的，可是我跑了两个数据集beauty office_product[这两个数据集都是在数据链接里下载的5-core数据集]，可是结果却如图上所示，您能告诉我一下这是什么原因呢？

**Comment by zfan20** [comment]
I have no idea why you got such inferior results, my peers even got better results than my reported ones. Also, even your reported results, are still better than SASRec. The possible reason might be different initializations caused by different machines. 

I grid searched all hyperparameters and reported the test results based on the best validation MRR. You may try to do the same thing and see if other settings work better.

**Comment by TTJ520** [comment]
好的谢谢
